// // src/lib/contestsData.js
// export const contests = [
//   {
//     id: "1",
//     title: "Cricket Mega Contest",
//     description: "Win big with your cricket knowledge!",
//     image: "https://placehold.co/600x300?text=Cricket",
//     category: "Recommended",
//     prize: "₹50,000",
//     entry: "₹49",
//     participants: ["Rahul", "Amit", "Sneha"],
//   },
//   {
//     id: "2",
//     title: "Football Frenzy",
//     description: "Predict and win football matches!",
//     image: "https://placehold.co/600x300?text=Football",
//     category: "Popular",
//     prize: "₹10,000",
//     entry: "₹0",
//     participants: ["Abhishek", "Kunal"],
//   },
//   {
//     id: "3",
//     title: "Esports Battle",
//     description: "Join the Esports challenge now.",
//     image: "https://placehold.co/600x300?text=Esports",
//     category: "Starting Soon",
//     prize: "₹5,000",
//     entry: "₹25",
//     participants: ["Rohit"],
//   },
//   {
//     id: "4",
//     title: "Fantasy League Showdown",
//     description: "Compete with friends in fantasy league.",
//     image: "https://placehold.co/600x300?text=Fantasy",
//     category: "Recommended",
//     prize: "₹20,000",
//     entry: "₹30",
//     participants: ["Aman", "Vikas"],
//   },
//   {
//     id: "5",
//     title: "Tennis Smash",
//     description: "Predict tennis outcomes and win.",
//     image: "https://placehold.co/600x300?text=Tennis",
//     category: "Popular",
//     prize: "₹15,000",
//     entry: "₹10",
//     participants: ["Rahul", "Sneha"],
//   },
//   {
//     id: "6",
//     title: "Basketball Bonanza",
//     description: "Join the basketball challenge.",
//     image: "https://placehold.co/600x300?text=Basketball",
//     category: "Starting Soon",
//     prize: "₹8,000",
//     entry: "₹20",
//     participants: ["Kunal", "Rohit"],
//   },
//   {
//     id: "7",
//     title: "Hockey Heroes",
//     description: "Test your hockey knowledge!",
//     image: "https://placehold.co/600x300?text=Hockey",
//     category: "Recommended",
//     prize: "₹25,000",
//     entry: "₹50",
//     participants: ["Amit", "Abhishek"],
//   },
//   {
//     id: "8",
//     title: "Kabaddi Clash",
//     description: "Predict Kabaddi matches accurately.",
//     image: "https://placehold.co/600x300?text=Kabaddi",
//     category: "Popular",
//     prize: "₹12,000",
//     entry: "₹15",
//     participants: ["Vikas", "Rohit"],
//   },
//   {
//     id: "9",
//     title: "Chess Championship",
//     description: "Join the ultimate chess contest.",
//     image: "https://placehold.co/600x300?text=Chess",
//     category: "Starting Soon",
//     prize: "₹7,000",
//     entry: "₹5",
//     participants: ["Rahul"],
//   },
//   {
//     id: "10",
//     title: "Cricket Super League",
//     description: "Join the mega cricket league.",
//     image: "https://placehold.co/600x300?text=Cricket+SL",
//     category: "Recommended",
//     prize: "₹60,000",
//     entry: "₹60",
//     participants: ["Amit", "Sneha"],
//   },
//   {
//     id: "11",
//     title: "Football Frenzy 2",
//     description: "Second edition football contest.",
//     image: "https://placehold.co/600x300?text=Football2",
//     category: "Popular",
//     prize: "₹20,000",
//     entry: "₹20",
//     participants: ["Abhishek", "Vikas"],
//   },
//   {
//     id: "12",
//     title: "Esports Battle 2",
//     description: "Compete in Esports 2.0!",
//     image: "https://placehold.co/600x300?text=Esports2",
//     category: "Starting Soon",
//     prize: "₹10,000",
//     entry: "₹25",
//     participants: ["Rohit", "Aman"],
//   },
//   {
//     id: "13",
//     title: "Fantasy League Mania",
//     description: "Biggest fantasy league contest.",
//     image: "https://placehold.co/600x300?text=Fantasy2",
//     category: "Recommended",
//     prize: "₹35,000",
//     entry: "₹40",
//     participants: ["Rahul", "Amit"],
//   },
//   {
//     id: "14",
//     title: "Tennis Smash 2",
//     description: "Second tennis contest edition.",
//     image: "https://placehold.co/600x300?text=Tennis2",
//     category: "Popular",
//     prize: "₹18,000",
//     entry: "₹15",
//     participants: ["Sneha", "Kunal"],
//   },
//   {
//     id: "15",
//     title: "Basketball Bonanza 2",
//     description: "Basketball 2.0 challenge.",
//     image: "https://placehold.co/600x300?text=Basketball2",
//     category: "Starting Soon",
//     prize: "₹9,000",
//     entry: "₹25",
//     participants: ["Abhishek", "Rohit"],
//   },
//   {
//     id: "16",
//     title: "Hockey Heroes 2",
//     description: "Second hockey heroes contest.",
//     image: "https://placehold.co/600x300?text=Hockey2",
//     category: "Recommended",
//     prize: "₹30,000",
//     entry: "₹50",
//     participants: ["Vikas", "Aman"],
//   },
//   {
//     id: "17",
//     title: "Kabaddi Clash 2",
//     description: "Kabaddi contest 2nd edition.",
//     image: "https://placehold.co/600x300?text=Kabaddi2",
//     category: "Popular",
//     prize: "₹14,000",
//     entry: "₹20",
//     participants: ["Rahul", "Sneha"],
//   },
//   {
//     id: "18",
//     title: "Chess Championship 2",
//     description: "Chess contest 2nd edition.",
//     image: "https://placehold.co/600x300?text=Chess2",
//     category: "Starting Soon",
//     prize: "₹8,000",
//     entry: "₹5",
//     participants: ["Rohit", "Abhishek"],
//   },
//   {
//     id: "19",
//     title: "Cricket Mega Contest 2",
//     description: "Cricket contest 2nd edition.",
//     image: "https://placehold.co/600x300?text=Cricket2",
//     category: "Recommended",
//     prize: "₹55,000",
//     entry: "₹60",
//     participants: ["Amit", "Vikas"],
//   },
//   {
//     id: "20",
//     title: "Football Frenzy 3",
//     description: "Football contest 3rd edition.",
//     image: "https://placehold.co/600x300?text=Football3",
//     category: "Popular",
//     prize: "₹25,000",
//     entry: "₹25",
//     participants: ["Abhishek", "Rohit"],
//   },
// ];


// src/data/contests.js

export const contests = [
  {
    id: "1",
    title: "Cricket League",
    description: "Win prizes predicting winners",
    type: "single", // single | double | group | weekly | monthly | daily
    prize: "₹5000",
    entry: "₹50",
    image: "https://placekitten.com/400/200",
    participants: ["Ravi", "Aman"],
    popular: true,
  },
  {
    id: "2",
    title: "Weekly Coding Contest",
    description: "Solve coding problems",
    type: "weekly",
    prize: "₹2000",
    entry: "Free",
    image: "https://placekitten.com/401/200",
    participants: ["Neha", "Karan"],
    startSoon: true,
  },
];

// 🔥 Generate more dummy contests
for (let i = 3; i <= 500; i++) {
  const types = ["daily", "weekly", "monthly", "group", "single", "double"];
  const randomType = types[Math.floor(Math.random() * types.length)];

  contests.push({
    id: String(i),
    title: `${randomType.toUpperCase()} Contest ${i}`,
    description: `Join the ${randomType} challenge and win exciting rewards!`,
    type: randomType,
    prize: `₹${(Math.floor(Math.random() * 10) + 1) * 1000}`,
    entry: Math.random() > 0.5 ? "Free" : `₹${(Math.floor(Math.random() * 5) + 1) * 50}`,
    image: `https://placekitten.com/${400 + (i % 10)}/${200 + (i % 5)}`,
    participants: [
      "Aman",
      "Ravi",
      "Neha",
      "Karan",
      "Pooja",
      "Arjun",
      "Simran",
      "Vivek",
    ].slice(0, Math.floor(Math.random() * 5) + 2),
    popular: Math.random() > 0.7,
    startSoon: Math.random() > 0.8,
  });
}
